changelog:
  categories:
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Packaging and documentation
      labels:
        - packaging
        - documentation
    - title: Other changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
