/*
 * Forcing the desktop font, without paying for it on every scroll.
 *
 * The obvious way is a user stylesheet: `* { font-family: X !important }` at
 * user origin, which is the one level that beats the page's own !important.
 * It works, and it is expensive -- every element in every row WhatsApp recycles
 * down a scrolling conversation has to have its font resolved against a rule
 * that matches everything. Measured on a live chat, the same 2100px of
 * scrolling blocked the main thread for 212ms with that sheet and 82ms without,
 * with the worst single stall going from 82ms to 139ms. That is the difference
 * between a scroll that glides and one that catches.
 *
 * So the substitution is moved to where a browser does it: fontconfig, at font
 * lookup, once per family rather than once per element. A private config is
 * written that includes the system one and then renames the families WhatsApp
 * asks for to the family the desktop is set to. Chromium reads it because
 * FONTCONFIG_FILE points at it, and nothing in the page has to change.
 */
'use strict';

const fs = require('fs');
const path = require('path');

/* What WhatsApp Web's own stack names, plus the two generic faces fontconfig
   would otherwise answer with on a Linux desktop. Emoji families are absent on
   purpose: they are what the desktop font falls through to for the glyphs it
   does not have, and rebinding them would draw every emoji as a blank box. */
const REPLACED = [
  'Roboto Variable', 'Roboto', 'Roboto Flex',
  'Segoe UI', 'Segoe UI Variable', 'system-ui', '-apple-system',
  'BlinkMacSystemFont', 'Helvetica', 'Helvetica Neue', 'Arial',
  'Liberation Sans', 'DejaVu Sans', 'Cantarell', 'Adwaita Sans', 'Inter',
];

/* Emoji, and the faces a script the desktop font does not cover falls through
   to. Rebinding any of these would draw every emoji as a blank box and every
   Arabic word in the wrong script's glyphs. */
const NEVER = new Set([
  'noto color emoji', 'apple color emoji', 'segoe ui emoji', 'segoe ui symbol',
  'noto sans arabic', 'noto naskh arabic', 'emoji', 'monospace', 'serif',
  'cursive', 'fantasy', 'ui-monospace', 'ui-serif',
  /* Generics, which the <alias> at the bottom of the config already handles.
     Rewriting one as if it were a family name is how a config ends up telling
     fontconfig that sans-serif is literally called "sans-serif". */
  'sans-serif', 'inherit', 'initial', 'unset', 'revert',
]);

/* Families the page turned out to ask for that the list above does not cover.
   WhatsApp changes its font stack from time to time -- it currently leads with
   "Roboto Variable", which was not in any list written before it appeared -- so
   the page reports what it actually asks for and it is added here. fontconfig
   is read once per process, so a family learned now takes effect on the next
   start; there is no way to make that live, and it costs one launch. */
const learn = (dir, families) => {
  const file = path.join(dir, 'learned-fonts.json');
  let known = [];
  try { known = JSON.parse(fs.readFileSync(file, 'utf8')); } catch (e) { /* first run */ }

  const wanted = families
    .map(name => name.trim().replace(/^["']|["']$/g, ''))
    .filter(name => name && !NEVER.has(name.toLowerCase()))
    .filter(name => !REPLACED.some(k => k.toLowerCase() === name.toLowerCase()))
    .filter(name => !known.some(k => k.toLowerCase() === name.toLowerCase()));

  if (!wanted.length) return [];
  known = [...known, ...wanted].slice(-32);
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file, JSON.stringify(known, null, 2));
  } catch (e) { /* the next start will learn it again */ }
  return wanted;
};

const learned = dir => {
  try { return JSON.parse(fs.readFileSync(path.join(dir, 'learned-fonts.json'), 'utf8')); }
  catch (e) { return []; }
};

const escapeXml = value => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const document_ = (family, extra = []) => {
  const target = escapeXml(family);
  const rules = [...REPLACED, ...extra]
    .filter(name => name.toLowerCase() !== family.toLowerCase())
    .map(name => `  <match target="pattern">
    <test name="family"><string>${escapeXml(name)}</string></test>
    <edit name="family" mode="assign" binding="strong"><string>${target}</string></edit>
  </match>`)
    .join('\n');

  return `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by whatsapp-desktop. Do not edit: it is rewritten on every start
     from the desktop's own interface font. -->
<fontconfig>
  <include ignore_missing="yes">/etc/fonts/fonts.conf</include>

${rules}

  <!-- and the generic the page falls through to when it names nothing else -->
  <alias binding="strong">
    <family>sans-serif</family>
    <prefer><family>${target}</family></prefer>
  </alias>
</fontconfig>
`;
};

/*
 * Writes the config and returns its path, or null when it could not be written
 * -- in which case the caller simply does not set FONTCONFIG_FILE and the page
 * is drawn in WhatsApp's own fonts, which is a cosmetic loss and nothing worse.
 */
const configure = (family, dir) => {
  if (!family) return null;
  const file = path.join(dir, 'fonts.conf');
  try {
    fs.mkdirSync(dir, { recursive: true });
    const wanted = document_(family, learned(dir));
    /* Rewritten only when it changed: fontconfig caches per file, and touching
       it on every start would throw that cache away for nothing. */
    let current = '';
    try { current = fs.readFileSync(file, 'utf8'); } catch (e) { /* first run */ }
    if (current !== wanted) fs.writeFileSync(file, wanted);
    return file;
  } catch (e) {
    console.warn('could not write %s: %s', file, e.message);
    return null;
  }
};

module.exports = { configure, learn, REPLACED };
